// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaVendas.Data;

#nullable disable

namespace SistemaVendas.Migrations
{
    [DbContext(typeof(SistemaVendasDBContext))]
    [Migration("20230615001927_InitialDB")]
    partial class InitialDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SistemaVendas.Models.ClienteModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SistemaVendas.Models.DistribuidoraModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("cep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cnpj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome_distribuidora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Distribuidoras");
                });

            modelBuilder.Entity("SistemaVendas.Models.ItensNFeModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("cofins")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("icms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_nfe")
                        .HasColumnType("int");

                    b.Property<int>("id_produto")
                        .HasColumnType("int");

                    b.Property<string>("ipi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("iss")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("quantidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("total_cofins_produto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("total_icms_produto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("total_ipi_produto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("total_iss_produto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("total_pis_produto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("valor_total_produto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("valor_unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("id_nfe");

                    b.HasIndex("id_produto");

                    b.ToTable("ItensNFes");
                });

            modelBuilder.Entity("SistemaVendas.Models.MarcaModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("cnpj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome_marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("SistemaVendas.Models.NFeModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("id_distribuidora")
                        .HasColumnType("int");

                    b.Property<int>("num_nfe")
                        .HasColumnType("int");

                    b.Property<string>("total_cofins")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("total_icms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("total_ipi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("total_iss")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("total_pis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("valortotal_nfe")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("id_distribuidora");

                    b.ToTable("NFes");
                });

            modelBuilder.Entity("SistemaVendas.Models.ProdutoModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("cod_barras")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("id_marca")
                        .HasColumnType("int");

                    b.Property<string>("nome_produto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("preco_venda")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.HasIndex("id_marca");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("SistemaVendas.Models.ProdutoVendaModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("id_produto")
                        .HasColumnType("int");

                    b.Property<int>("id_venda")
                        .HasColumnType("int");

                    b.Property<string>("quantidade")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("id_produto");

                    b.HasIndex("id_venda");

                    b.ToTable("ProdutoVendas");
                });

            modelBuilder.Entity("SistemaVendas.Models.UsuarioModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("nomeusuario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("role")
                        .HasMaxLength(150)
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaVendas.Models.VendaModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("data_venda")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_cliente")
                        .HasColumnType("int");

                    b.Property<string>("metodo_pagamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("precototal_venda")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("id_cliente");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("SistemaVendas.Models.ItensNFeModel", b =>
                {
                    b.HasOne("SistemaVendas.Models.NFeModel", "NFe")
                        .WithMany()
                        .HasForeignKey("id_nfe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaVendas.Models.ProdutoModel", "Produto")
                        .WithMany()
                        .HasForeignKey("id_produto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NFe");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("SistemaVendas.Models.NFeModel", b =>
                {
                    b.HasOne("SistemaVendas.Models.DistribuidoraModel", "Distribuidora")
                        .WithMany()
                        .HasForeignKey("id_distribuidora")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distribuidora");
                });

            modelBuilder.Entity("SistemaVendas.Models.ProdutoModel", b =>
                {
                    b.HasOne("SistemaVendas.Models.MarcaModel", "Marca")
                        .WithMany()
                        .HasForeignKey("id_marca")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("SistemaVendas.Models.ProdutoVendaModel", b =>
                {
                    b.HasOne("SistemaVendas.Models.ProdutoModel", "Produto")
                        .WithMany()
                        .HasForeignKey("id_produto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaVendas.Models.VendaModel", "Venda")
                        .WithMany()
                        .HasForeignKey("id_venda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("SistemaVendas.Models.VendaModel", b =>
                {
                    b.HasOne("SistemaVendas.Models.ClienteModel", "Cliente")
                        .WithMany()
                        .HasForeignKey("id_cliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
